### ISSUE TITLE
support a custom fetch wrapper or implementation

### ISSUE THREAD

**Issue by aliceriot** [mitodl/redux-hammock#6]
We'll need this for our own use-case, so that we can use it with our `fetchJSONWithCSRF` function.

I'm going to change the `Endpoint` object to allow the user to specify a fetch implementation or wrapper (something with basically the same API, of `fetch(url: string, options: Object)`), or default to `window.fetch`.

**Comment by aliceriot** [comment]
@noisecapella what do you think about pulling our `fetchJSONWithCSRF` and `fetchWithCSRF` functions out into this library as well? We could export them so that users who want to use `hammock` with Django would be good to go, and it would allow us to use the same implementations of those functions across our projects.

Of course, another option would be to put those in another library, but I think it may make sense to have them here.

**Comment by noisecapella** [comment]
Yeah, I agree putting them here makes sense
